language: node_js
node_js:
    - "4"
services:
    - mysql
    - redis
before_install:
    - mysql -e 'CREATE DATABASE janusvr;'
    - mysql janusvr < test/db/testdb.sql
    - cp config-example.js config.js
    - ./generate_key_ni

